In [1]:
import duckdb
import pandas as pd

# Configuration immédiate
duckdb.execute("SET force_download=true")
duckdb.execute("SET threads TO 4")  # Utilise plusieurs threads pour accélérer

In [2]:
# Supprimer les anciennes vues
duckdb.execute("DROP VIEW IF EXISTS titles")
duckdb.execute("DROP VIEW IF EXISTS ratings")
duckdb.execute("DROP VIEW IF EXISTS actors")
duckdb.execute("DROP VIEW IF EXISTS name")
duckdb.execute("DROP VIEW IF EXISTS crew")
duckdb.execute("DROP VIEW IF EXISTS akas")

In [3]:
url_titles = 'https://datasets.imdbws.com/title.basics.tsv.gz'
url_ratings = 'https://datasets.imdbws.com/title.ratings.tsv.gz'
url_actors = 'https://datasets.imdbws.com/title.principals.tsv.gz'
url_akas = "https://datasets.imdbws.com/title.akas.tsv.gz"
url_tmdb = 'D:/Utilisateurs/Dylan Malis/Téléchargements/tmdb_full.csv'
url_crew = "https://datasets.imdbws.com/title.crew.tsv.gz"
url_name = "https://datasets.imdbws.com/name.basics.tsv.gz"

In [4]:
duckdb.query(f"CREATE OR REPLACE VIEW titles AS SELECT * FROM read_csv_auto('{url_titles}')")
duckdb.query(f"CREATE OR REPLACE VIEW tmdb AS SELECT * FROM read_csv_auto('{url_tmdb}')")
duckdb.query(f"CREATE OR REPLACE VIEW akas AS SELECT * FROM read_csv_auto('{url_akas}')")
duckdb.query(f"CREATE OR REPLACE VIEW crew AS SELECT * FROM read_csv_auto('{url_crew}')")
duckdb.query(f"CREATE OR REPLACE VIEW name AS SELECT * FROM read_csv_auto('{url_name}')")
duckdb.query(f"CREATE OR REPLACE VIEW rating AS SELECT * FROM read_csv_auto('{url_ratings}')")

In [5]:
import pandas as pd
pd.set_option('display.max_rows', 500)

query_finale = """
    SELECT titles.tconst, tmdb.original_title, titles.primaryTitle, akas.title, akas.attributes, akas.types, akas.ordering,  titles.startYear,titles.runtimeMinutes,akas.language, tmdb.spoken_languages,titles.genres, name.primaryName,name.primaryProfession, name.knownForTitles, rating.averageRating,tmdb.popularity,tmdb.tagline, tmdb.overview,tmdb.poster_path, tmdb.video, tmdb.budget,tmdb.revenue
    FROM titles
    LEFT JOIN tmdb ON imdb_id = titles.tconst
    LEFT JOIN akas ON akas.titleId = titles.tconst
    LEFT JOIN crew ON crew.tconst = titles.tconst
    LEFT JOIN name ON name.nconst = crew.directors
    LEFT JOIN rating ON rating.tconst = titles.tconst
    WHERE titles.titleType = 'movie'
    AND titles.tconst NOT LIKE '%\\N%'
    AND titles.isAdult = 0
    AND titles.genres IS NOT NULL
    AND titles.genres NOT LIKE '%\\N%'
    AND titles.genres NOT LIKE '%Horror%'
    AND titles.genres NOT LIKE '%NaN%'
    AND titles.runtimeMinutes NOT LIKE '%\\N%'
    AND CAST(titles.runtimeMinutes AS INTEGER) >= 80
    AND CAST(titles.runtimeMinutes AS INTEGER) <= 220
    AND akas.region = 'FR' AND tmdb.spoken_languages LIKE '%fr%'
    AND titles.startYear NOT LIKE '%\\N%'
    AND CAST(titles.startYear as INTEGER) BETWEEN 1960 AND 2027
    AND tmdb.status != 'Canceled'
    AND rating.averageRating >= 5.0

    
"""
# on viens de rajouter le filtre rating, mais pas tester.
#akas.region = 'FR' AND
#AND tmdb.spoken_languages LIKE '%fr%'

In [6]:
# EXÉCUTER LA REQUÊTE ET OBTENIR LE RÉSULTAT
df = duckdb.query(query_finale).to_df()
df.head(50)

,tconst,original_title,primaryTitle,title,attributes,types,ordering,startYear,runtimeMinutes,language,...,primaryProfession,knownForTitles,averageRating,popularity,tagline,overview,poster_path,video,budget,revenue
0,tt0756648,Le Renard et l'Enfant,The Fox and the Child,Le Renard et l'Enfant,\N,imdbDisplay,19,2007,92,\N,...,"director,writer,cinematographer","tt0428803,tt4466550,tt2873250,tt0756648",6.8,7.265,NaN,A young girl of about 10 years lives in a soli...,/eBpc03hS9A7QPv0k6AZfDCdKURt.jpg,False,13000000,29610210
1,tt0758442,Nuit noire,Black Night,Nuit noire,\N,imdbDisplay,5,2005,90,\N,...,"director,writer,producer","tt0758442,tt0236953,tt3613036,tt0219929",6.5,1.495,NaN,"In a world overtaken by eternal darkness, the ...",/o4FEvQXuTKUOFcQNSIim1biac1l.jpg,False,0,0
2,tt0759509,Changement d'adresse,Change of Address,Changement d'adresse,\N,imdbDisplay,9,2006,85,\N,...,"director,writer,actor","tt12443930,tt14831708,tt7530986,tt1700467",6.7,2.767,NaN,"In Paris, the emotional and professional tribu...",/our6U7TsUTXbVWdSNHfupV6Lzlg.jpg,False,0,0
3,tt0762142,Les 3 p'tits cochons,The 3 L'il Pigs,Les 3 p'tits cochons,\N,imdbDisplay,7,2007,124,\N,...,"actor,director,writer","tt0479647,tt1756750,tt4738174,tt0186895",6.9,1.350,NaN,"As their mother lies in a coma, two brothers d...",/tQDU7JCWRZTM8rhPmnNmmQQkBgP.jpg,False,0,4400000
4,tt0765141,La Question humaine,Heartbeat Detector,La question humaine,\N,imdbDisplay,5,2007,143,\N,...,"director,writer,editor","tt0262674,tt0412518,tt7290778,tt0765141",6.2,0.738,NaN,A psychologist discovers troubling links betwe...,/sSvZmKs7ltOOHbUXEWl1CNLb8vP.jpg,False,0,0
5,tt0765142,Qui m'aime me suive,"If You Love Me, Follow Me",Qui m'aime me suive,\N,imdbDisplay,7,2006,102,\N,...,"director,writer,producer","tt2914386,tt1175298,tt0347678,tt0273895",6.1,1.236,NaN,Thirty-five-year-old Max has a successful care...,/9B78LYo6OMXCABunjNX999alEHd.jpg,False,0,0
6,tt0765263,Un ami parfait,Un ami parfait,Un ami parfait,\N,imdbDisplay,2,2006,106,\N,...,"director,actor,writer","tt0086988,tt0284573,tt0072320,tt0117303",5.5,0.840,NaN,"""Julien Rossi wakes up in a hospital bed and f...",/w7z3NPJCZ4sZt0qIr5ssHUmAtSL.jpg,False,0,0
7,tt0765432,Der Baader Meinhof Komplex,The Baader Meinhof Complex,La bande à Baader,\N,imdbDisplay,24,2008,150,\N,...,"director,writer,producer","tt0765432,tt0082176,tt2293522,tt0097714",7.3,10.244,NaN,'Der Baader Meinhof Komplex' depicts the polit...,/4D1MllpbRMt6DDsSCxQxbl2JYM5.jpg,False,27000000,26937355
8,tt0765469,El Pasado,The Past,El pasado,\N,imdbDisplay,4,2007,114,\N,...,"director,writer,producer","tt0293007,tt0082912,tt0120674,tt0089424",6.1,1.005,NaN,"After 12 years, Sofía and Rímini decided to se...",/1BxoNZ6kxoKsr2RUlU17IagvtQE.jpg,False,0,0
9,tt0769508,Dans Paris,Dans Paris,Dans Paris,\N,imdbDisplay,7,2006,89,\N,...,"writer,director,actor","tt0996605,tt7534054,tt1263778,tt32086069",6.3,5.293,NaN,"Paul, depressed from his recent break-up with ...",/92O2VOf6U3qqYTIUmCqaHMqjbW9.jpg,False,0,0
10,tt0772105,L'amico di famiglia,The Family Friend,L'ami de la famille,\N,\N,13,2006,102,\N,...,"writer,producer,director","tt12680684,tt3312830,tt2358891,tt1440345",7.1,6.440,NaN,"Geremia, an aging tailor/money lender, is a re...",/4GErGIgZuhRbwMH9fYSQcZTeShT.jpg,False,0,0
11,tt0772157,Broken English,Broken English,Broken English,\N,imdbDisplay,5,2007,93,\N,...,"director,actress,writer","tt0772157,tt3752902,tt5885894,tt1329988",6.3,6.660,So Many Mr. Wrongs. So Few Mr. Rights.,Nora Wilder is freaking out. Everyone around h...,/nzRi0qkBsRDKIXPGJJ5BJ5WtFSv.jpg,False,2000000,0
12,tt0774756,Désaccord Parfait,Twice Upon a Time,Désaccord parfait,\N,imdbDisplay,9,2006,92,\N,...,"actor,director,producer","tt0119307,tt2313389,tt0235606,tt0774756",5.7,2.166,NaN,Alice d'Abanville and Louis Ruinard are two ex...,/nHNGywnzkqakVNPV3eI3g6Bqt5.jpg,False,0,0
13,tt0775489,L'Illusionniste,The Illusionist,L'illusionniste,\N,imdbDisplay,9,2010,80,\N,...,"director,writer,animation_department","tt0286244,tt0775489,tt0401711,tt0127710",7.4,12.347,"When life loses its wonder, all it takes is on...",A French illusionist travels to Scotland to wo...,/Ac2tNYW9sRaOhmtMJQuhf2mvo00.jpg,False,18000000,6007194
14,tt0774756,Désaccord Parfait,Twice Upon a Time,Remake,\N,working,15,2006,92,\N,...,"actor,director,producer","tt0119307,tt2313389,tt0235606,tt0774756",5.7,2.166,NaN,Alice d'Abanville and Louis Ruinard are two ex...,/nHNGywnzkqakVNPV3eI3g6Bqt5.jpg,False,0,0
15,tt0778784,Mon Meilleur Ami,My Best Friend,Mon meilleur ami,\N,imdbDisplay,10,2006,90,\N,...,"director,writer,camera_department","tt0100112,tt0144201,tt0117477,tt0301414",6.6,5.717,It takes a lifetime to learn the meaning of fr...,Catherine refuses to believe that her business...,/hPqtG8L5fj9PUlW7Gldb218FyIc.jpg,False,0,0
16,tt0779722,Amnesia: The James Brighton Enigma,Amnesia: The James Brighton Enigma,Amnésie: L'énigme James Brighton,\N,\N,6,2005,90,\N,...,"writer,director,producer","tt0779722,tt0298293,tt0116228,tt7477812",6.2,2.041,NaN,A young man wakes up naked on a pallet on the ...,/v4rgOwSQOSFvU48dBtvLGYgYn3b.jpg,False,0,0
17,tt0781435,Ne touchez pas la hache,The Duchess of Langeais,Ne touchez pas la hache,\N,imdbDisplay,3,2007,137,\N,...,"director,writer,actor","tt0101428,tt0242994,tt0094709,tt0054156",6.5,2.423,NaN,"General Montriveau, having returned from the N...",/bGpyGXPgPyv8lmluq766Wk9ziX0.jpg,False,0,0
18,tt0783233,Atonement,Atonement,Reviens-moi,\N,imdbDisplay,22,2007,123,\N,...,"director,producer,miscellaneous","tt0414387,tt0783233,tt4555426,tt0993842",7.8,17.881,Torn apart by betrayal. Separated by war. Boun...,"As a 13-year-old, fledgling writer Briony Tall...",/hMRIyBjPzxaSXWM06se3OcNjIQa.jpg,False,30000000,131016624
19,tt0783530,Je te mangerais,You Will Be Mine,Je te mangerais,\N,imdbDisplay,4,2009,96,\N,...,"sound_department,actress,director","tt0783530,tt0401711,tt0293058,tt0298126",5.6,4.766,NaN,Marie leaves home to study the piano at the co...,/ksMUhT6tKLvLWJ5ndS7pVLl1WAe.jpg,False,3000000,0
20,tt0783665,Au delà de la haine,Beyond Hatred,Au delà de la haine,\N,imdbDisplay,2,2005,86,\N,...,"director,writer,producer","tt0783665,tt2528104,tt0970174,tt27861889",6.7,0.991,NaN,"In this deeply moving, award-winning French do...",/2NJFGHbrPK8J1Vug93RvBhSSRAQ.jpg,False,0,0
21,tt0783705,Dans les cordes,On the Ropes,Dans les cordes,\N,imdbDisplay,2,2007,93,\N,...,"writer,director,miscellaneous","tt2248731,tt4857616,tt0783705,tt0423713",5.9,0.660,NaN,NaN,/lKbg3BSA3xYJbLAiJJZ1TFjy0vh.jpg,False,0,0
22,tt0785076,Vent mauvais,Ill Wind,Vent mauvais,\N,imdbDisplay,3,2007,92,\N,...,"director,writer,producer","tt0785076,tt6922654,tt0482684",5.8,1.459,NaN,NaN,/gQWzw1YtoBGHxmPK55hhNKS96xa.jpg,False,0,0
23,tt0787523,Towelhead,Towelhead,Tabou(s),\N,dvd,26,2007,124,\N,...,"producer,writer,miscellaneous","tt0169547,tt0248654,tt0844441,tt11327514",6.9,6.706,How can you find yourself if no one can see you?,A young Arab-American girl struggles with her ...,/8h035i9cXx64QToQOCp7GBwFHqN.jpg,False,0,367638
24,tt0790602,Nitro,Nitro,Absolute Race,\N,imdbDisplay,10,2007,105,\N,...,"director,writer,actor","tt0239271,tt0317668,tt4738174,tt1625015",5.4,2.534,NaN,Max leads a good life with Alice and their son...,/iYiHJHIAkrdEQ8qQITARkBKslnK.jpg,False,0,0
25,tt0791304,Georgia Rule,Georgia Rule,"Mère-fille, mode d'emploi",\N,\N,33,2007,113,\N,...,"writer,producer,actor","tt0104694,tt0151738,tt0100405,tt0791304",5.9,10.181,"Mother. Daughter. Grandmother. In this family,...","Georgia Rule follows a rebellious, uncontrolla...",/68kFdluafITRWdPQBHySrn7wPNu.jpg,False,20000000,25000167
26,tt0792947,Les ambitieux,So Ambitious,Les Ambitieux,\N,imdbDisplay,16,2006,90,\N,...,"director,writer,actress","tt13321730,tt4080768,tt2369497,tt8260226",6.0,1.141,NaN,"On the one hand you have Judith Zahn, an arrog...",/7Y0gKaSU4S87gS4AsLkDcfBJqOM.jpg,False,0,0
27,tt0792948,Les Anges exterminateurs,The Exterminating Angels,Portraits nus,\N,working,23,2006,100,\N,...,"director,writer,actor","tt0287963,tt0094959,tt0103932,tt0234663",5.4,8.667,NaN,A filmmaker holds a series of boundary-pushing...,/i74vevQ9Q7kWNlzSUzyTguiRLg4.jpg,False,0,154210
28,tt0792959,Danse avec lui,Dance with Him,Danse avec lui,\N,imdbDisplay,3,2007,118,\N,...,"writer,director,actress","tt0792959,tt5085178,tt0304417,tt0388242",6.1,4.031,NaN,Three years after simultaneously parting with ...,/fC5mMi6BuFyinR4qFf1LH05UAIy.jpg,False,0,0
29,tt0792965,"Ensemble, c'est tout",Hunting and Gathering,"Ensemble, c'est tout",\N,imdbDisplay,10,2007,97,\N,...,"producer,actor,writer","tt0091288,tt0107002,tt0063771,tt0792965",6.7,13.578,Love might be closer than you think.,"When Camille falls ill, she is forced to live ...",/dNgTyFxp84SWeOkgdWeZDiXsADG.jpg,False,0,0
30,tt0792966,La faute à Fidel!,Blame it on Fidel,La faute à Fidel!,\N,imdbDisplay,4,2006,99,\N,...,"director,assistant_director,actress","tt0792966,tt0109592,tt1572502,tt0422015",7.5,2.375,NaN,A 9-year-old girl weathers big changes in her ...,/p6mBGtAryMefx0dBQwB8Qpyhu2I.jpg,False,0,0
31,tt0792975,L'invité,L'invité,L'invité,\N,imdbDisplay,5,2007,86,\N,...,"director,writer,producer","tt0117815,tt0207943,tt0168270,tt0211073",5.5,5.377,NaN,"Fifty years old, three years past of unemploym...",/liNUP5DCJz2g7YwzsrPAZtQ5GAj.jpg,False,0,0
32,tt0792978,Mia et le Migou,Mia and the Migoo,Mia et le Migou,\N,imdbDisplay,8,2008,92,\N,...,"producer,art_department,director","tt0365659,tt0792978,tt1671584,tt1673702",6.6,3.161,NaN,One night Mia has a premonition. So after sayi...,/bTTxuvQMvsqSqpMXz33yH2WiDOH.jpg,False,0,0
33,tt0792985,Paul dans sa vie,Paul dans sa vie,Paul dans sa vie,\N,imdbDisplay,2,2005,103,\N,...,"director,writer,cinematographer","tt32546437,tt0792985,tt32258772",7.6,0.600,NaN,Paul Bedel will be 75 soon. He's and old bache...,/bDHlcJF2oJiBEnj0hJFU8ZVAXNI.jpg,False,0,0
34,tt0792992,Tous à l'ouest: Une aventure de Lucky Luke,Go West: A Lucky Luke Adventure,Tous à l'Ouest : Une aventure de Lucky Luke,\N,imdbDisplay,21,2007,90,\N,...,"director,writer,animation_department","tt3032300,tt0792992,tt2046005,tt0118343",6.3,4.860,NaN,"The Daltons have escaped to New York, where th...",/bP5i9zLWzMz2DJ9msmqB27w3GDP.jpg,False,0,0
35,tt0792997,Les yeux bandés,Les yeux bandés,Les yeux bandés,\N,imdbDisplay,2,2007,81,\N,...,"writer,director,actor","tt9350920,tt2891070,tt21348598,tt5078326",5.7,0.600,NaN,NaN,/wT7YpJcO9GTNDPNE4C2AQTI8mQR.jpg,False,0,0
36,tt0792948,Les Anges exterminateurs,The Exterminating Angels,Les anges exterminateurs,\N,imdbDisplay,14,2006,100,\N,...,"director,writer,actor","tt0287963,tt0094959,tt0103932,tt0234663",5.4,8.667,NaN,A filmmaker holds a series of boundary-pushing...,/i74vevQ9Q7kWNlzSUzyTguiRLg4.jpg,False,0,154210
37,tt0795341,Bled Number One,Bled Number One,Bled Number One,\N,imdbDisplay,4,2006,100,\N,...,"director,writer,producer","tt4223932,tt0795341,tt10292050,tt0312014",6.2,1.400,NaN,"Hardly freed from a French prison, Kamel is de...",/jBtiZVKsjxHO3bx8TLlKTu8Kmoi.jpg,False,0,0
38,tt0795370,Le Deuxième souffle,The Second Wind,Le Deuxième Souffle,\N,imdbDisplay,9,2007,155,\N,...,"writer,director,assistant_director","tt0103110,tt0098000,tt0318725,tt0075082",5.7,1.737,NaN,"Gu, a famous gangster, has just escaped from j...",/kHQNYnjEZpQqca1u07aCYqBg20I.jpg,False,34000000,0
39,tt0796335,Molière,Molière,Molière,\N,imdbDisplay,7,2007,120,\N,...,"writer,director,actor","tt12105554,tt0796335,tt1264904,tt0289688",7.1,7.320,NaN,"Molière, a down-and-out actor-cum-playwright u...",/3nfp9JCCzt1QlRhEzQfz5EkjLYn.jpg,False,0,0
40,tt0798820,"Ici Najac, à vous la Terre","Ici Najac, à vous la terre","Ici Najac, à vous la terre",\N,imdbDisplay,2,2006,97,\N,...,"director,writer,producer","tt0798820,tt0254976,tt4536682,tt0072602",7.1,0.600,NaN,A few inhabitants from a village in Aveyron st...,NaN,False,0,0
41,tt0799932,Barakat!,Barakat!,Barakat!,\N,imdbDisplay,3,2006,95,\N,...,"director,writer,editorial_department","tt1842435,tt0799932,tt0219490,tt0377881",6.3,1.400,NaN,Set amidst the civil war of Algeria in the 199...,/d5GLQEzabErbE9IiJBux5PEnvTq.jpg,False,0,0
42,tt0800135,Mon colonel,The Colonel,Mon colonel,\N,imdbDisplay,6,2006,110,\N,...,"assistant_director,writer,director","tt0800135,tt5736758,tt2294727,tt33086904",7.0,0.709,NaN,"A ""Reformed Colonel"" is found dead in Paris, a...",/j7uzNau9xUsoNuYBNEytFsSSotA.jpg,False,3900000,0
43,tt0800241,TransSiberian,Transsiberian,Transsibérien,\N,tv,26,2008,111,\N,...,"director,producer,writer","tt0261983,tt0361862,tt0800241,tt4669264",6.6,9.706,You can't escape your lies.,A TransSiberian train journey from China to Mo...,/dhTOda5CLp9tEdDzQZiqBTdv5lR.jpg,False,15000000,5926410
44,tt0801514,Moments choisis des Histoire(s) du cinéma,Chosen Moments of Historie(s) of Cinema,Moments choisis des histoire(s) du cinéma,\N,imdbDisplay,4,2001,84,\N,...,"director,writer,editor","tt0057869,tt0056663,tt0057345,tt0058898",7.1,0.741,NaN,A very personal look at the history of cinema ...,/1ifpFq9FGPv3HxnP1rf74sz9PRy.jpg,False,0,0
45,tt0804540,Taxi 4,Taxi 4,Taxi 4,\N,imdbDisplay,8,2007,91,\N,...,"camera_department,director,writer","tt0281364,tt0804540,tt0091287,tt0183869",5.6,12.845,NaN,Before being extradited to Africa to stand tri...,/8OoVXQo23kgMw4ooLfi2mDGVfUE.jpg,False,17500000,65125001
46,tt0804540,Taxi 4,Taxi 4,T4xi,poster title,\N,17,2007,91,\N,...,"camera_department,director,writer","tt0281364,tt0804540,tt0091287,tt0183869",5.6,12.845,NaN,Before being extradited to Africa to stand tri...,/8OoVXQo23kgMw4ooLfi2mDGVfUE.jpg,False,17500000,65125001
47,tt0806029,L'Affaire Farewell,Farewell,L'affaire Farewell,\N,imdbDisplay,9,2009,113,\N,...,"director,writer,actor","tt0424205,tt0240149,tt13234058,tt14586118",6.9,8.282,Some secrets have the power to change the cour...,An intricate thriller about an ordinary man th...,/mxwlffx1g16uyasYcnEeHYSWXmp.jpg,False,0,0
48,tt0806029,L'Affaire Farewell,Farewell,The Farewell Affair,literal English title,\N,14,2009,113,\N,...,"director,writer,actor","tt0424205,tt0240149,tt13234058,tt14586118",6.9,8.282,Some secrets have the power to change the cour...,An intricate thriller about an ordinary man th...,/mxwlffx1g16uyasYcnEeHYSWXmp.jpg,False,0,0
49,tt0808151,Angels & Demons,Angels & Demons,Anges et Démons,alternative spelling,\N,41,2009,138,\N,...,"producer,actor,writer","tt0367279,tt0268978,tt0075213,tt0112384",6.7,37.919,The holiest event of our time. Perfect for the...,Harvard symbologist Robert Langdon is recruite...,/hrvNVd0GDeytbDhduWa3SFKmg4A.jpg,False,150000000,485930816

In [7]:
df.describe()

          ordering  averageRating   popularity        budget       revenue
count  9336.000000    9336.000000  9336.000000  9.336000e+03  9.336000e+03
mean      9.610219       6.349625     5.493379  3.226555e+06  8.292680e+06
std       8.509112       0.722326    19.414076  1.618360e+07  5.859733e+07
min       2.000000       5.000000     0.600000  0.000000e+00  0.000000e+00
25%       4.000000       5.800000     1.233000  0.000000e+00  0.000000e+00
50%       7.000000       6.300000     2.528000  0.000000e+00  0.000000e+00
75%      12.000000       6.900000     6.388000  0.000000e+00  0.000000e+00
max     115.000000       9.400000  1170.178000  2.700000e+08  2.264162e+09

In [8]:
df.shape

(9336, 23)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9336 entries, 0 to 9335
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   tconst             9336 non-null   str
 1   original_title     9336 non-null   str
 2   primaryTitle       9336 non-null   str
 3   title              9336 non-null   str
 4   attributes         9336 non-null   str
 5   types              9336 non-null   str
 6   ordering           9336 non-null   int64
 7   startYear          9336 non-null   str
 8   runtimeMinutes     9336 non-null   str
 9   language           9336 non-null   str
 10  spoken_languages   9336 non-null   str
 11  genres             9336 non-null   str
 12  primaryName        8626 non-null   str
 13  primaryProfession  8626 non-null   str
 14  knownForTitles     8626 non-null   str
 15  averageRating      9336 non-null   float64
 16  popularity         9336 non-null   float64
 17  tagline            1866 non-null   str
 18  overview           9038 non-null   str
 19  poster_path        9026 non-null   str
 20  video              9336 non-null   bool
 21  budget             9336 non-null   int64
 22  revenue            9336 non-null   int64
dtypes: bool(1), float64(2), int64(3), str(17)
memory usage: 1.6 MB

In [10]:
df.to_csv(
    "resultats_cinema3.csv",
    sep=";",
    index=False,
    encoding="utf-8-sig"
)