In [1]:
import duckdb
import pandas as pd

# Configuration immédiate
duckdb.execute("SET force_download=true")
duckdb.execute("SET threads TO 4")  # Utilise plusieurs threads pour accélérer

In [2]:
# Supprimer les anciennes vues
duckdb.execute("DROP VIEW IF EXISTS titles")
duckdb.execute("DROP VIEW IF EXISTS ratings")
duckdb.execute("DROP VIEW IF EXISTS actors")
duckdb.execute("DROP VIEW IF EXISTS name")
duckdb.execute("DROP VIEW IF EXISTS crew")
duckdb.execute("DROP VIEW IF EXISTS akas")

In [3]:
url_titles = 'https://datasets.imdbws.com/title.basics.tsv.gz'
url_ratings = 'https://datasets.imdbws.com/title.ratings.tsv.gz'
url_actors = 'https://datasets.imdbws.com/title.principals.tsv.gz'
url_akas = "https://datasets.imdbws.com/title.akas.tsv.gz"
url_tmdb = 'D:/Utilisateurs/Dylan Malis/Téléchargements/tmdb_full.csv'
url_crew = "https://datasets.imdbws.com/title.crew.tsv.gz"
url_name = "https://datasets.imdbws.com/name.basics.tsv.gz"

In [4]:
duckdb.query(f"CREATE OR REPLACE VIEW titles AS SELECT * FROM read_csv_auto('{url_titles}')")
duckdb.query(f"CREATE OR REPLACE VIEW tmdb AS SELECT * FROM read_csv_auto('{url_tmdb}')")
duckdb.query(f"CREATE OR REPLACE VIEW akas AS SELECT * FROM read_csv_auto('{url_akas}')")
duckdb.query(f"CREATE OR REPLACE VIEW crew AS SELECT * FROM read_csv_auto('{url_crew}')")
duckdb.query(f"CREATE OR REPLACE VIEW name AS SELECT * FROM read_csv_auto('{url_name}')")
duckdb.query(f"CREATE OR REPLACE VIEW rating AS SELECT * FROM read_csv_auto('{url_ratings}')")

In [5]:
import pandas as pd
pd.set_option('display.max_rows', 500)

query_test = """
SELECT titles.tconst, tmdb.original_title, titles.primaryTitle, akas.title, akas.attributes, akas.types, akas.ordering,  titles.startYear,titles.runtimeMinutes,akas.language, tmdb.spoken_languages,titles.genres, name.primaryName,name.primaryProfession, name.knownForTitles, rating.averageRating,tmdb.popularity,tmdb.tagline, tmdb.overview,tmdb.poster_path, tmdb.video, tmdb.budget,tmdb.revenue
    FROM titles
    LEFT JOIN tmdb ON imdb_id = titles.tconst
    LEFT JOIN akas ON akas.titleId = titles.tconst
    LEFT JOIN crew ON crew.tconst = titles.tconst
    LEFT JOIN name ON name.nconst = crew.directors
    LEFT JOIN rating ON rating.tconst = titles.tconst
    WHERE titles.tconst = 'tt0119116'
    AND akas.region = 'FR'
    LIMIT 1000
"""

In [6]:
dftest = duckdb.query(query_test).to_df()
dftest.head(100)

,tconst,original_title,primaryTitle,title,attributes,types,ordering,startYear,runtimeMinutes,language,...,primaryProfession,knownForTitles,averageRating,popularity,tagline,overview,poster_path,video,budget,revenue
0,tt0119116,The Fifth Element,The Fifth Element,Le Cinquième Élément,\N,imdbDisplay,35,1997,126,\N,...,"writer,producer,director","tt0119116,tt2872732,tt0110413,tt0100263",7.6,46.823,There is no future without it.,"In 2257, a taxi driver is unintentionally give...",/fPtlCO1yQtnoLHOwKtWz7db6RGU.jpg,False,90000000,263920180

In [9]:
import pandas as pd
pd.set_option('display.max_rows', 500)

query_finale = """
    SELECT titles.tconst, tmdb.original_title, titles.primaryTitle, akas.title, akas.attributes, akas.types, akas.ordering,  titles.startYear,titles.runtimeMinutes,akas.language, tmdb.spoken_languages,titles.genres, name.primaryName,name.primaryProfession, name.knownForTitles, rating.averageRating,tmdb.popularity,tmdb.tagline, tmdb.overview,tmdb.poster_path, tmdb.video, tmdb.budget,tmdb.revenue
    FROM titles
    LEFT JOIN tmdb ON imdb_id = titles.tconst
    LEFT JOIN akas ON akas.titleId = titles.tconst
    LEFT JOIN crew ON crew.tconst = titles.tconst
    LEFT JOIN name ON name.nconst = crew.directors
    LEFT JOIN rating ON rating.tconst = titles.tconst
    WHERE titles.titleType = 'movie'
    AND titles.tconst NOT LIKE '%\\N%'
    AND titles.isAdult = 0
    AND titles.genres IS NOT NULL
    AND titles.genres NOT LIKE '%\\N%'
    AND titles.genres NOT LIKE '%Horror%'
    AND titles.genres NOT LIKE '%NaN%'
    AND titles.runtimeMinutes NOT LIKE '%\\N%'
    AND CAST(titles.runtimeMinutes AS INTEGER) >= 80
    AND CAST(titles.runtimeMinutes AS INTEGER) <= 220
    AND akas.region = 'FR' AND (tmdb.spoken_languages LIKE '%fr%' OR tmdb.spoken_languages LIKE '%en%')
    AND titles.startYear NOT LIKE '%\\N%'
    AND CAST(titles.startYear as INTEGER) BETWEEN 1960 AND 2027
    AND tmdb.status != 'Canceled'
    AND rating.averageRating >= 5.0

    
"""
# on viens de rajouter le filtre rating, mais pas tester.
#akas.region = 'FR' AND
#AND tmdb.spoken_languages LIKE '%fr%'

In [10]:
# EXÉCUTER LA REQUÊTE ET OBTENIR LE RÉSULTAT
df = duckdb.query(query_finale).to_df()
df.head(50)

,tconst,original_title,primaryTitle,title,attributes,types,ordering,startYear,runtimeMinutes,language,...,primaryProfession,knownForTitles,averageRating,popularity,tagline,overview,poster_path,video,budget,revenue
0,tt0052205,The Small World of Sammy Lee,The Small World of Sammy Lee,Les folles nuits de Sammy Lee,\N,imdbDisplay,10,1963,107,\N,...,"writer,director,producer","tt0062803,tt0082812,tt0054403,tt0061452",7.1,1.960,Soho... Where Love Comes Cheap... Money Comes ...,The compère of a seedy strip club struggles to...,/4Trt44jLU4rTRYg7JK8dbVdXNfe.jpg,False,0,0
1,tt0052376,War Is Hell,War Is Hell,Héros de guerre,\N,imdbDisplay,9,1961,81,\N,...,"producer,director,writer","tt0065815,tt0074377,tt0053332,tt0052739",5.3,1.400,IRON-GUTS GUYS IN ACTION!,"During the Korean War, a glory-hunting sergean...",/4QyQdnsLNzfGeN1Gzu6xMa7EUz2.jpg,False,0,0
2,tt0052607,The Battle of the Sexes,The Battle of the Sexes,La bataille des sexes,\N,\N,13,1960,84,\N,...,"director,editor,writer","tt0095159,tt0037635,tt0045201,tt0044829",6.6,3.273,NaN,Angela Barrows is a man-eating business woman ...,/i3b1RowQT7IqUyU99xmA3CaQAOt.jpg,False,0,0
3,tt0052614,Le Bel Âge,Le bel âge,Le bel âge,\N,imdbDisplay,3,1960,100,\N,...,"director,writer,assistant_director","tt0052614,tt0057635,tt0208040,tt0158774",6.8,1.400,NaN,"Steph, Jean-Claude and Jacques work in a Paris...",/98Z5yPoNIm8sQeyep5cpr5NHov9.jpg,False,0,0
4,tt0052680,Cash McCall,Cash McCall,Cet homme est un requin,\N,\N,12,1960,102,\N,...,"director,actor,producer","tt0060028,tt0051051,tt0050681,tt0042953",6.4,3.742,High finance and high romance are about to merge.,Wealthy hotshot Cash McCall makes his money by...,/v0wUowsxFuYVm2VvmIty2lZqUoO.jpg,False,0,0
5,tt0052686,Certains l'aiment... froide,Some Like It... Cold,Certains l'aiment... froide!,\N,imdbDisplay,7,1960,90,\N,...,"assistant_director,director,writer","tt0315099,tt0054394,tt0052686,tt0159605",5.2,1.916,NaN,The old Valmorin died 200 years ago. The notar...,/nWxNWddjRO14xGOiHU770oDfXsV.jpg,False,0,0
6,tt0052698,Classe tous risques,The Big Risk,Classe tous risques,\N,imdbDisplay,8,1960,103,\N,...,"writer,director,assistant_director","tt0105682,tt0113947,tt0064165,tt0075975",7.5,5.843,Tough Gangster Action,"On crowded Milan streets, two men execute a sp...",/uMiuUAlPwiWDKSgu4SoShpzvMR.jpg,False,0,0
7,tt0052745,A Dog of Flanders,A Dog of Flanders,L'Orphelin et son chien,\N,imdbDisplay,13,1960,96,\N,...,"director,editor,miscellaneous","tt0033729,tt0058241,tt0050105,tt0064708",7.2,1.400,Wonderful family entertainment the whole world...,"The emotional story of a boy, his grandfather,...",/sf50zn1FhPxf8tvvlsYTYadkSAv.jpg,False,0,0
8,tt0052769,L'Eau à la bouche,L'eau à la bouche,L'eau à la bouche,\N,imdbDisplay,11,1960,85,\N,...,"director,actor,writer","tt0054838,tt0066041,tt0210108,tt0053725",6.1,1.400,NaN,Miléna is living in her grandmother's baroque ...,/nq4i6WvKAZokanPCz2wXIDqDKc0.jpg,False,0,0
9,tt0052781,Era notte a Roma,Escape by Night,Les Évadés de la nuit,\N,imdbDisplay,29,1960,82,\N,...,"writer,director,producer","tt0038823,tt0038890,tt0046511,tt0039417",7.1,1.782,NaN,"In Nazi-occupied Rome, a beautiful bootlegger,...",/7k40hZ9b5pMIUge74mZgY40yOdL.jpg,False,0,0
10,tt0052811,The Flesh and the Fiends,The Flesh and the Fiends,L'impasse aux Violences,\N,imdbDisplay,14,1960,94,\N,...,"director,writer,assistant_director","tt0056350,tt0049248,tt0044931,tt0053958",6.9,2.618,Coffins Looted! Cadavers Dissected!,Edinburgh surgeon Dr. Robert Knox requires cad...,/9crqR3YowhiT7UMb7FEZTVfKFXf.jpg,False,0,0
11,tt0052832,The Fugitive Kind,The Fugitive Kind,L'homme à la peau de serpent,\N,imdbDisplay,17,1960,119,\N,...,"director,writer,producer","tt0292963,tt0050083,tt0071877,tt0070666",7.0,5.982,With a guitar and a snake skin jacket he drift...,"Val Xavier, a drifter of obscure origins, arri...",/ta2ircBtQs8EZXe6QznCI5J6N3i.jpg,False,0,0
12,tt0052925,Muerte al amanecer,Death at Dawn,Nuits et Violences,reissue title,\N,8,1960,94,\N,...,"writer,producer,director","tt0062121,tt0147560,tt0078987,tt0812228",5.5,0.600,NaN,"The prestigious composer Virgilio Delise, susp...",/2170JSXsyehLtOviXbanmjE2Plp.jpg,False,0,0
13,tt0052997,The League of Gentlemen,The League of Gentlemen,Hold-up à Londres,\N,imdbDisplay,20,1960,116,\N,...,"director,producer,writer","tt0053242,tt0037635,tt0039398,tt0042265",7.2,5.157,What is the league ... Who are the gentlemen ?,Involuntarily-retired Colonel Hyde recruits se...,/6lJvpL5Z3qZxegmJHUpjGsWROtW.jpg,False,0,0
14,tt0053063,Meurtre en 45 tours,Meurtre en 45 tours,Meurtre en 45 tours,\N,imdbDisplay,11,1960,98,\N,...,"director,writer,actor","tt0054701,tt0053063,tt0071799,tt0076526",5.9,1.415,NaN,Danielle Darrieux stars in this French thrille...,/8kXXSe92K9gq1Z8OaRFtjnGVQ7h.jpg,False,0,0
15,tt0053149,Oscar Wilde,Oscar Wilde,Oscar Wilde,\N,imdbDisplay,5,1960,96,\N,...,"actor,director,producer","tt0042192,tt0023302,tt0044981,tt0051028",6.8,1.435,At last it can be told… He shocked the world!,"England, 1891. Ascending writer Oscar Wilde (1...",/tNSNxogmQgf6gZHe28Igm6vy7py.jpg,False,0,0
16,tt0053244,The Savage Innocents,The Savage Innocents,Les dents du diable,\N,\N,19,1960,110,\N,...,"director,writer,actor","tt0048545,tt0075675,tt0042593,tt0079261",6.8,4.001,"Savage, sensational drama in this fantastic ad...",An Eskimo who has had little contact with whit...,/oDBKyJhZgMKZBVaXhGdNmN6ePMS.jpg,False,0,0
17,tt0053255,Les scélérats,The Wretches,Les scélérats,\N,imdbDisplay,5,1960,90,\N,...,"actor,director,writer","tt0084340,tt0056404,tt0058922,tt0053130",6.4,1.400,NaN,Meant to be a psychological study of a dysfunc...,/ljjWYeicWylZsk4uK0vgrWT9s0t.jpg,False,0,0
18,tt0053273,The Shakedown,The Shakedown,Chantage à Soho,\N,imdbDisplay,3,1960,92,\N,...,"producer,director,writer","tt0320048,tt0054898,tt0050015,tt0219455",6.7,0.600,Models were the bait for BLACKMAIL!,Augie comes out of prison and finds his old vi...,/8YtWTbBBm7BxLoEekjC3E8r1Vnm.jpg,False,0,0
19,tt0053279,Le Signe du Lion,Sign of the Lion,Le signe du lion,\N,imdbDisplay,17,1962,103,\N,...,"director,writer,actor","tt0064612,tt0086087,tt0065772,tt0137439",7.2,2.998,NaN,An American in Paris lives by sponging off his...,/b5jY3jyISYMY0ReGjqtbgaPq7dr.jpg,False,0,0
20,tt0053365,Too Hot to Handle,Playgirl After Dark,La blonde et les nus de Soho,\N,\N,13,1960,90,\N,...,"director,writer,miscellaneous","tt0055928,tt0059800,tt0057076,tt0062467",5.8,1.717,The sizzler you read about in Playboy magazine...,A French reporter working on a steamy story ab...,/ytw9sldnsbrJly4WvbejJ3BcXJL.jpg,False,0,0
21,tt0053371,A Touch of Larceny,A Touch of Larceny,Un brin d'escroquerie,\N,\N,10,1960,93,\N,...,"director,assistant_director,writer","tt0070328,tt0058150,tt0071807,tt0066995",6.7,1.400,About Money and Women and How To Get 'Em...Wit...,"After falling in love with an American woman, ...",/vFGg8eKloPHeswYQwdkyvwN1XWq.jpg,False,0,0
22,tt0053440,I Aim at the Stars,I Aim at the Stars,L'Homme des fusées secrètes,\N,imdbDisplay,26,1960,107,\N,...,"director,writer,producer","tt0054953,tt0051204,tt0068408,tt0055824",6.2,0.600,FROM THE EARTH TO THE STARS...this is the stor...,The life story of the famed rocket scientist D...,/tuwdJzeyq7bRvZIOxC6iNBBhN67.jpg,False,0,0
23,tt0053472,À bout de souffle,Breathless,À bout de souffle,\N,imdbDisplay,15,1960,90,\N,...,"director,writer,editor","tt0057869,tt0056663,tt0057345,tt0058898",7.6,13.450,NaN,A small-time thief steals a car and impulsivel...,/9Wx0Wdn2EOqeCZU4SP6tlS3LOml.jpg,False,0,0
24,tt0053561,Five Branded Women,5 Branded Women,Jovanka et les autres,\N,alternative,41,1960,101,\N,...,"director,actor,producer","tt0057163,tt0059749,tt0079638,tt0051878",6.6,2.531,All The Savage Ravishing Passions of War!,Five Yugoslav women who consorted with the Ger...,/wE8KR917jBjNekoa1L6feYiCosu.jpg,False,0,0
25,tt0053571,The Adventures of Huckleberry Finn,The Adventures of Huckleberry Finn,Les aventuriers du fleuve,\N,\N,14,1960,107,\N,...,"director,writer,actor","tt0034583,tt0029843,tt0026174,tt0037913",6.2,4.897,The most exciting adventures a boy ever had! H...,"From chicken thief to cabin boy, riverboat pil...",/l2bmntngk2bQyrWT7Z9CxMNE8fO.jpg,False,1357000,2750000
26,tt0053577,오발탄,Aimless Bullet,Une balle perdue,\N,imdbDisplay,10,1961,110,\N,...,"director,editor,producer","tt0322188,tt0322753,tt0321571,tt0322719",7.2,2.272,Let's get outta here!,"Two brothers—Chul-ho, an accountant with a too...",/4O53U5HYkdw4HN6mpJmvxqfPi7U.jpg,False,0,0
27,tt0053580,The Alamo,The Alamo,Alamo,\N,imdbDisplay,8,1960,162,\N,...,"actor,producer,miscellaneous","tt0065126,tt0056217,tt0045061,tt0075213",6.8,13.580,The Mission That Became a Fortress! The Fortre...,The legendary true story of a small band of so...,/54KNQfJnYZwhI3sPYyjXtptWGfg.jpg,False,12000000,7900000
28,tt0053583,All the Young Men,All the Young Men,Les marines attaquent,\N,\N,9,1960,87,\N,...,"writer,producer,director","tt0067705,tt0056908,tt0070248,tt0077326",6.2,1.834,Spit out what's on your filthy little mind ......,"During the Korean War, the lieutenant in charg...",/9VBKvc3LwGUxlUV05h3uvZ2H443.jpg,False,1000000,2000000
29,tt0053597,Un amore a Roma,Un amore a Roma,L'Inassouvie,\N,imdbDisplay,10,1960,107,\N,...,"director,writer,actor","tt0056512,tt0072037,tt0062080,tt0062370",6.7,1.761,NaN,A young impoverished aristocrat and struggling...,/lcOxMUjkF2MIOCLBj6z5vFOcZ2l.jpg,False,0,0
30,tt0053601,The Angel Wore Red,The Angel Wore Red,L'ange pourpre,\N,\N,8,1960,99,\N,...,"writer,producer,director","tt0045891,tt0032551,tt0049474,tt0045029",5.8,0.887,Man of Faith-And a Faithless Woman!,A clergyman travels to Spain to join the Loyal...,/lnoXpSpuYhxihKCWMct9uNWybVZ.jpg,False,0,0
31,tt0053602,The Angry Silence,The Angry Silence,Le silence de la colère,\N,\N,14,1960,95,\N,...,"director,cinematographer,camera_department","tt0038574,tt0053602,tt0059573,tt0039195",7.2,4.672,"Rough, Tough, Deeply Moving",A young factory worker stands alone against a ...,/hXQtp9KOgqisXO73WkjiRJnh9mE.jpg,False,0,0
32,tt0053604,The Apartment,The Apartment,La garçonnière,\N,\N,39,1960,125,\N,...,"writer,director,producer","tt0053604,tt0053291,tt0047437,tt0043014",8.3,17.990,"Movie-wise, there has never been anything like...",Bud Baxter is a minor clerk in a huge New York...,/dmaRf8ROeSmg4duvFeMLq2ULnk3.jpg,False,3000000,25000000
33,tt0053617,Aventuras de Joselito y Pulgarcito,Adventures of Joselito and Tom Thumb,La Chanson de l'orphelin,\N,imdbDisplay,9,1960,87,\N,...,"actor,director,writer","tt0053241,tt0063090,tt0228227,tt0057857",5.6,1.648,NaN,Joselito lives with his grandmother in a fishi...,/x9SMNeZji0ijUnOc5F3qIgDExXI.jpg,False,0,0
34,tt0053619,L'avventura,L'Avventura,L'avventura,\N,imdbDisplay,5,1960,144,\N,...,"writer,director,editor","tt0060176,tt0053619,tt0073580,tt0054130",7.7,10.079,A new adventure in filmmaking...,"Claudia and Anna join Anna's lover, Sandro, on...",/waQPqPYLouGJXDYGqXmpyLN4PLA.jpg,False,0,0
35,tt0053622,BUtterfield 8,BUtterfield 8,La Vénus au vison,alternative spelling,\N,31,1960,109,\N,...,"director,miscellaneous","tt0044509,tt0048563,tt0049830,tt0048191",6.3,8.071,She must hold many men in her arms to find the...,"The story about Gloria Wandrous, a promiscuous...",/zwMaEBrNWFv9I9NiJVNTQ8znAM4.jpg,False,0,0
36,tt0053635,Le Baron de l'écluse,Le baron de l'écluse,Le baron de l'écluse,\N,imdbDisplay,16,1960,92,\N,...,"director,writer,editor","tt0042401,tt0039004,tt0050669,tt0045122",6.5,1.400,NaN,The lucky Baron wins a boat in a card game and...,/dfeHglGViXpjH9g0LZukxskKEGX.jpg,False,0,0
37,tt0053638,Austerlitz,The Battle of Austerlitz,Austerlitz,\N,imdbDisplay,7,1960,122,\N,...,"writer,director,editor","tt0014417,tt0025027,tt0018192,tt0066855",6.2,4.167,NaN,Napoleon Bonaparte crowns himself emperor and ...,/5RNpfejpbwsw4jUUgeUasUvNdhi.jpg,False,0,0
38,tt0053641,Because They're Young,Because They're Young,Le mal d'être jeune,\N,imdbDisplay,6,1960,102,\N,...,"director,producer","tt0066864,tt0052606,tt0058816,tt0052847",5.9,0.600,"Whoever you are, you're in this picture! Becau...",Director Paul Wendkos' 1960 film adaptation of...,/3hGiYzNK4oAxjazmnWq4meBDcNJ.jpg,False,0,0
39,tt0053645,Bells Are Ringing,Bells Are Ringing,Un numéro du tonnerre,\N,\N,26,1960,126,\N,...,"director,miscellaneous,music_department","tt0043278,tt0051658,tt0039116,tt0037059",6.9,3.176,NaN,Ella Peterson works in the basement office of ...,/fATfcGV05lvenYdXBBTEhvTyrRm.jpg,False,0,0
40,tt0053650,Beyond the Curtain,Beyond the Curtain,Derrière le rideau,\N,imdbDisplay,7,1960,88,\N,...,"writer,director,editor","tt2833218,tt0038924,tt0249780,tt0042646",5.9,1.520,NaN,A British flight officer plans to rescue an ai...,/o8Z0NGFxSmvXKuXYAQbvikC51M.jpg,False,0,0
41,tt0053660,Bluebeard's 10 Honeymoons,Bluebeard's Ten Honeymoons,La Dixième femme de Barbe Bleue,\N,imdbDisplay,9,1960,92,\N,...,"director,producer,writer","tt0042807,tt0047877,tt0047149,tt0144620",6.1,1.051,The Man With The Do-It-Yourself Murder Kit!,A murderer enriches his finances by marrying a...,/irPyT66rJx89YAbSazEriVbtAi3.jpg,False,0,0
42,tt0053663,Le Bois des amants,Le bois des amants,Le bois des amants,\N,imdbDisplay,13,1960,95,\N,...,"director,writer,costume_designer","tt0038476,tt0049877,tt0047432,tt0045569",5.7,1.400,NaN,NaN,/7oPJ9pFTn9JDkQtjCHQEeohUAOm.jpg,False,0,0
43,tt0053666,Les bonnes femmes,The Good Girls,Les bonnes femmes,\N,imdbDisplay,19,1960,100,\N,...,"director,writer,actor","tt0051404,tt0112769,tt0096336,tt0120018",7.2,3.031,NaN,Four Parisian women navigate the world of roma...,/lro6PSrHaO97BTWgJqYC47uvtba.jpg,False,0,0
44,tt0053672,The Boy and the Pirates,The Boy and the Pirates,Jimmy et les pirates,\N,imdbDisplay,10,1960,82,\N,...,"director,producer,writer","tt0074540,tt0075989,tt0050118,tt0068892",5.2,2.876,Boy Against Buccaneer!,Jimmy desires to be a pirate when one day he d...,/1nJ6V9ryJhfIho0f4z2nmcQLKIf.jpg,False,0,0
45,tt0053673,The Bramble Bush,The Bramble Bush,Le buisson ardent,\N,\N,11,1960,93,\N,...,"director,producer,actor","tt0086942,tt0055353,tt0118648,tt0081414",5.7,0.600,You can't put out the human fires that burn in...,A young doctor returns to his Massachusetts ho...,/8b7wj3Gyntlemb3ER2KZM8tD3Z6.jpg,False,0,0
46,tt0053675,A Breath of Scandal,A Breath of Scandal,Un scandale à la cour,\N,\N,25,1960,97,\N,...,"director,writer,actor","tt0034583,tt0029843,tt0026174,tt0037913",5.6,3.629,"You'll Find Yourself in a Whirlpool of Wine, W...",A European princess jeopardizes her crown when...,/7SGZGMxFhaHU0gu6RDWtFlFgkif.jpg,False,0,0
47,tt0053683,The Bulldog Breed,The Bulldog Breed,Norman dans la marine,\N,imdbDisplay,14,1960,97,\N,...,"assistant_director,director,production_manager","tt0054518,tt0056478,tt0062551,tt13173474",6.1,2.016,From The Army's Funniest Private...To The Navy...,"Norman Puckle, a well-meaning but clumsy groce...",/57ZDmjcPF6T85DKlkkT6xxUW540.jpg,False,0,0
48,tt0053690,Can-Can,Can-Can,Can-Can,\N,\N,10,1960,131,\N,...,"director,writer,miscellaneous","tt0049408,tt0045592,tt0053690,tt0019211",6.3,4.138,The Entertainment Event of the Year!,Parisian nightclub owner Simone Pistache is kn...,/d5ehuoO6KbyB6B6ooO0dOl5nhtS.jpg,False,6000000,0
49,tt0053695,Le Capitaine Fracasse,Captain Fracasse,Le capitaine Fracasse,\N,imdbDisplay,14,1961,108,\N,...,"writer,director,editor","tt0056485,tt0053695,tt0062689,tt0061222",6.1,2.962,NaN,"A ruined Baron Philippe de baron, meets one da...",/scKuYcCNGJd5vsdHjkqpTPskFLE.jpg,False,0,0

In [11]:
df.describe()

           ordering  averageRating    popularity        budget       revenue
count  26195.000000   26195.000000  26195.000000  2.619500e+04  2.619500e+04
mean      13.314449       6.360199     10.531008  8.661224e+06  2.391708e+07
std       10.704109       0.756025     58.617900  2.653033e+07  1.030815e+08
min        2.000000       5.000000      0.600000  0.000000e+00  0.000000e+00
25%        6.000000       5.800000      1.936000  0.000000e+00  0.000000e+00
50%       10.000000       6.300000      5.286000  0.000000e+00  0.000000e+00
75%       18.000000       6.900000     10.559000  2.300000e+06  1.356889e+06
max      150.000000       9.400000   4665.438000  5.793304e+08  2.923706e+09

In [12]:
df.shape

(26195, 23)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26195 entries, 0 to 26194
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   tconst             26195 non-null  str
 1   original_title     26195 non-null  str
 2   primaryTitle       26195 non-null  str
 3   title              26195 non-null  str
 4   attributes         26195 non-null  str
 5   types              26195 non-null  str
 6   ordering           26195 non-null  int64
 7   startYear          26195 non-null  str
 8   runtimeMinutes     26195 non-null  str
 9   language           26195 non-null  str
 10  spoken_languages   26195 non-null  str
 11  genres             26195 non-null  str
 12  primaryName        24245 non-null  str
 13  primaryProfession  24245 non-null  str
 14  knownForTitles     24245 non-null  str
 15  averageRating      26195 non-null  float64
 16  popularity         26195 non-null  float64
 17  tagline            14027 non-null  str
 18  overview           25858 non-null  str
 19  poster_path        25610 non-null  str
 20  video              26195 non-null  bool
 21  budget             26195 non-null  int64
 22  revenue            26195 non-null  int64
dtypes: bool(1), float64(2), int64(3), str(17)
memory usage: 4.4 MB

In [14]:
df.to_csv(
    "resultats_cinema4.csv",
    sep=";",
    index=False,
    encoding="utf-8-sig"
)