In [1]:
import duckdb
import pandas as pd

# Configuration immédiate
duckdb.execute("SET force_download=true")
duckdb.execute("SET threads TO 4")  # Utilise plusieurs threads pour accélérer

In [2]:
# Supprimer les anciennes vues
duckdb.execute("DROP VIEW IF EXISTS titles")
duckdb.execute("DROP VIEW IF EXISTS ratings")
duckdb.execute("DROP VIEW IF EXISTS actors")
duckdb.execute("DROP VIEW IF EXISTS name")
duckdb.execute("DROP VIEW IF EXISTS crew")
duckdb.execute("DROP VIEW IF EXISTS akas")

In [3]:
url_titles = 'https://datasets.imdbws.com/title.basics.tsv.gz'
url_ratings = 'https://datasets.imdbws.com/title.ratings.tsv.gz'
url_actors = 'https://datasets.imdbws.com/title.principals.tsv.gz'
url_akas = "https://datasets.imdbws.com/title.akas.tsv.gz"
url_tmdb = 'D:/Utilisateurs/Dylan Malis/Téléchargements/tmdb_full.csv'
url_crew = "https://datasets.imdbws.com/title.crew.tsv.gz"
url_name = "https://datasets.imdbws.com/name.basics.tsv.gz"

In [4]:
duckdb.query(f"CREATE OR REPLACE VIEW titles AS SELECT * FROM read_csv_auto('{url_titles}')")
duckdb.query(f"CREATE OR REPLACE VIEW tmdb AS SELECT * FROM read_csv_auto('{url_tmdb}')")
duckdb.query(f"CREATE OR REPLACE VIEW akas AS SELECT * FROM read_csv_auto('{url_akas}')")
duckdb.query(f"CREATE OR REPLACE VIEW crew AS SELECT * FROM read_csv_auto('{url_crew}')")
duckdb.query(f"CREATE OR REPLACE VIEW name AS SELECT * FROM read_csv_auto('{url_name}')")
duckdb.query(f"CREATE OR REPLACE VIEW rating AS SELECT * FROM read_csv_auto('{url_ratings}')")

In [ ]:
import pandas as pd
pd.set_option('display.max_rows', 500)

query_finale = """
    SELECT titles.tconst, titles.primaryTitle, akas.title, titles.startYear,titles.runtimeMinutes,tmdb.spoken_languages,titles.genres, name.primaryName,name.primaryProfession, name.knownForTitles, rating.averageRating,tmdb.popularity,tmdb.tagline, tmdb.overview,tmdb.poster_path, tmdb.video, tmdb.budget,tmdb.revenue
    FROM titles
    LEFT JOIN tmdb ON imdb_id = titles.tconst
    LEFT JOIN akas ON akas.titleId = titles.tconst
    LEFT JOIN crew ON crew.tconst = titles.tconst
    LEFT JOIN name ON name.nconst = crew.directors
    LEFT JOIN rating ON rating.tconst = titles.tconst
    WHERE titles.titleType = 'movie'
    AND titles.tconst NOT LIKE '%\\N%'
    AND titles.isAdult = 0
    AND titles.genres IS NOT NULL
    AND titles.genres NOT LIKE '%\\N%'
    AND titles.genres NOT LIKE '%Horror%'
    AND titles.genres NOT LIKE '%NaN%'
    AND titles.runtimeMinutes NOT LIKE '%\\N%'
    AND CAST(titles.runtimeMinutes AS INTEGER) >= 80
    AND CAST(titles.runtimeMinutes AS INTEGER) <= 220
    AND tmdb.spoken_languages LIKE '%fr%'
    AND titles.startYear NOT LIKE '%\\N%'
    AND CAST(titles.startYear as INTEGER) BETWEEN 1960 AND 2027
    AND tmdb.status != 'Canceled'
    AND rating.averageRating >= 5.0

    
"""
# on viens de rajouter le filtre rating, mais pas tester.
#akas.region = 'FR' AND

In [12]:
# EXÉCUTER LA REQUÊTE ET OBTENIR LE RÉSULTAT
df = duckdb.query(query_finale).to_df()
df.head(50)

,tconst,primaryTitle,title,startYear,runtimeMinutes,spoken_languages,genres,primaryName,primaryProfession,knownForTitles,averageRating,popularity,tagline,overview,poster_path,video,budget,revenue
0,tt0081176,My American Uncle,Mon oncle d'Amérique,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
1,tt0081176,My American Uncle,Min onkel fra Amerika,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
2,tt0081176,My American Uncle,My American Uncle,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
3,tt0081176,My American Uncle,My American Uncle,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
4,tt0081176,My American Uncle,Amerika no oji-san,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
5,tt0081176,My American Uncle,Amerikai nagybácsim,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
6,tt0081176,My American Uncle,Amerikalı Amcam,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
7,tt0081176,My American Uncle,Amerikan setä,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
8,tt0081176,My American Uncle,Dieu ne peut rien pour nous,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
9,tt0081176,My American Uncle,Mein Onkel aus Amerika,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
10,tt0081176,My American Uncle,Meu Tio da América,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
11,tt0081176,My American Uncle,Mi tío de América,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
12,tt0081176,My American Uncle,Min farbror från Amerika,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
13,tt0081176,My American Uncle,Min onkel i Amerika,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
14,tt0081176,My American Uncle,Mio zio d'America,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
15,tt0081176,My American Uncle,Muj strýcek z Ameriky,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
16,tt0081176,My American Uncle,My Uncle from America,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
17,tt0081176,My American Uncle,O Meu Tio da América,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
18,tt0081176,My American Uncle,Ông Chú Người Mỹ Của Tôi,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
19,tt0081176,My American Uncle,Unchiul meu din America,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
20,tt0081176,My American Uncle,Wujaszek z Ameryki,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
21,tt0081176,My American Uncle,Ο θείος μου από την Αμερική,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
22,tt0081176,My American Uncle,Mi tío de América,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
23,tt0081176,My American Uncle,Мій американський дядечко,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
24,tt0081176,My American Uncle,Мой американский дядюшка,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
25,tt0081176,My American Uncle,Чичо ми от Америка,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
26,tt0081176,My American Uncle,アメリカの伯父さん,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
27,tt0081176,My American Uncle,我的美国舅舅,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
28,tt0081176,My American Uncle,Mi tío de América,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
29,tt0081176,My American Uncle,Mi tío de América,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
30,tt0081176,My American Uncle,Mon oncle d'Amérique,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
31,tt0081176,My American Uncle,Mon oncle d'Amérique,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
32,tt0081176,My American Uncle,Mon oncle d'Amérique,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
33,tt0081176,My American Uncle,Min onkel fra Amerika,1980,125,['fr'],"Comedy,Drama,Romance",Alain Resnais,"director,editor,writer","tt0052893,tt0054632,tt0119828,tt0081176",7.6,7.760,NaN,Prof. Henri Laborit uses the stories of the li...,/1IV44owj1uZnD0bStusyY4PexP2.jpg,False,0,0
34,tt0081182,Death Watch,La mort en direct,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
35,tt0081182,Death Watch,Der gekaufte Tod,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
36,tt0081182,Death Watch,Der gekaufte Tod,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
37,tt0081182,Death Watch,La muerte en directo,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
38,tt0081182,Death Watch,La muerte en directo,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
39,tt0081182,Death Watch,A Morte ao Vivo,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
40,tt0081182,Death Watch,A Morte em Directo,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
41,tt0081182,Death Watch,De dood op het scherm,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
42,tt0081182,Death Watch,Death in Full View,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
43,tt0081182,Death Watch,Death Watch - Der gekaufte Tod,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
44,tt0081182,Death Watch,Direktsänd död,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
45,tt0081182,Death Watch,Death Watch,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
46,tt0081182,Death Watch,Halál egyenes adásban,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
47,tt0081182,Death Watch,Kameran ljuger aldrig,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
48,tt0081182,Death Watch,Katherine Mortenhoen Ostettu Kuolema,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0
49,tt0081182,Death Watch,La mort en direct,1980,117,"['en', 'fr', 'de']","Drama,Sci-Fi,Thriller",Bertrand Tavernier,"director,writer,producer","tt0088318,tt0071622,tt0115822,tt0186730",6.5,8.173,She's the target of every eye… including eyes ...,In a future world where the disease has been f...,/wSuvftmbs0fInDe69u8yDUtElsp.jpg,False,0,0

In [7]:
df.describe()

       averageRating    popularity        budget       revenue
count   10585.000000  10719.000000  1.071900e+04  1.071900e+04
mean        6.106982      5.159943  2.931698e+06  7.309966e+06
std         0.969484     18.240558  1.523542e+07  5.492054e+07
min         1.200000      0.600000  0.000000e+00  0.000000e+00
25%         5.500000      1.164000  0.000000e+00  0.000000e+00
50%         6.200000      2.299000  0.000000e+00  0.000000e+00
75%         6.800000      5.953500  0.000000e+00  0.000000e+00
max         9.400000   1170.178000  2.700000e+08  2.264162e+09

In [13]:
df.shape

(175826, 18)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 175826 entries, 0 to 175825
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   tconst             175826 non-null  str
 1   primaryTitle       175826 non-null  str
 2   title              175826 non-null  str
 3   startYear          175826 non-null  str
 4   runtimeMinutes     175826 non-null  str
 5   spoken_languages   175826 non-null  str
 6   genres             175826 non-null  str
 7   primaryName        162752 non-null  str
 8   primaryProfession  162752 non-null  str
 9   knownForTitles     162752 non-null  str
 10  averageRating      175328 non-null  float64
 11  popularity         175826 non-null  float64
 12  tagline            62285 non-null   str
 13  overview           173035 non-null  str
 14  poster_path        172847 non-null  str
 15  video              175826 non-null  bool
 16  budget             175826 non-null  int64
 17  revenue            175826 non-null  int64
dtypes: bool(1), float64(2), int64(2), str(13)
memory usage: 23.0 MB